// mp/src/components/pretty-time/pretty-time.vue
<template>
  <text>{{ formatted }}</text>
</template>

<script lang="ts" setup>
import type { ConfigType } from 'dayjs';
import dayjs from 'dayjs';
import { computed } from 'vue';

const props = defineProps<{ time: ConfigType }>();

const formatted = computed(() => {
  const now = dayjs();
  const current = dayjs(props.time);

  if (now.diff(current, 'd') <= 15) {
    return current.fromNow();
  }

  if (now.year() === current.year()) {
    return current.format('MM-DD');
  }

  return current.format('YYYY-MM-DD');
});
</script>

// web/src/components/PrettyTime/index.tsx
import React, { useMemo } from 'react';
import type { ConfigType } from 'dayjs';
import dayjs from 'dayjs';
import { Tooltip } from 'antd';

interface PrettyTimeProps {
  time: ConfigType;
}


const PrettyTime: React.FC<PrettyTimeProps> = ({ time }) => {
  const formatted = useMemo(() => {
    const now = dayjs();
    const current = dayjs(time);

    if (now.diff(current, 'd') <= 15) {
      return current.fromNow();
    }

    if (now.year() === current.year()) {
      return current.format('MM-DD HH:mm');
    }

    return current.format('YYYY-MM-DD HH:mm:ss');
  }, [time]);

  if (formatted !== dayjs(time).format('YYYY-MM-DD HH:mm:ss')) {
    return (
      <Tooltip title={dayjs(time).format('YYYY-MM-DD HH:mm:ss')}>
        {formatted}
      </Tooltip>
    );
  }

  return formatted;
};

export default PrettyTime;
